---
baseurl: ""
description: This is my place where I post my thoughts to share with others.
email: chris@crickertech.com
exclude:
  - script/
  - Vagrantfile
  - README.md
  - LICENSE
future: true
github_username: calef
plugins:
  - jekyll-feed
show_excerpts: true
theme: minima
title: Kachess
url: "https://kachess.dev"
